version: '3.3'
services:
  redis-local:
    image: redis:5.0.6
    expose:
      - 6379
  msg-printer-test:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm test
    environment:
      - REDIS_HOST=redis-local
    depends_on:
      - redis-local
